# Generated by Django 6.0.4 on 2026-04-18 03:24

import django.db.models.deletion
import django_choices_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_operacion', models.DateField(db_index=True)),
                ('estado', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Pendiente'), (2, 'Procesando'), (3, 'Servida'), (4, 'Pagada')], default=1, verbose_name='Estado')),
                ('cancelada', models.BooleanField(db_index=True, default=False)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('forma_pago', django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Efectivo'), (2, 'Tarjeta')], default=1, verbose_name='Forma de Pago')),
                ('efectivo_entregado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo entregado')),
                ('propina', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Propina Recibida')),
                ('importe_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('porc_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='% Descuento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_table', to='administracion.table')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('menu_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.menuproduct')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordenes.order')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fecha_operacion', 'estado', 'cancelada'], name='ordenes_ord_fecha_o_9bb69c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fecha_operacion', 'usuario', 'estado'], name='ordenes_ord_fecha_o_8dd4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fecha_operacion', 'usuario'], name='ordenes_ord_fecha_o_c6559a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fecha_operacion', 'numero_orden'], name='ordenes_ord_fecha_o_b0b19e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fecha_operacion', 'usuario', 'cancelada'], name='ordenes_ord_fecha_o_2f2bef_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fecha_operacion', 'usuario', 'mesa'], name='ordenes_ord_fecha_o_990ad0_idx'),
        ),
    ]
