# Generated by Django 6.0.4 on 2026-04-20 15:19

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Pendiente de Pago'), (2, 'Procesando'), (3, 'Servida'), (4, 'Pagada')], default=1, verbose_name='Estado'),
        ),
    ]
