# Generated by Django 6.0.4 on 2026-04-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_order_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='usuario',
        ),
    ]
