# Generated by Django 6.0.4 on 2026-04-22 22:30

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_orderitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=django_choices_field.fields.IntegerChoicesField(choices=[(1, 'Pendiente'), (2, 'Procesando'), (3, 'Servida'), (4, 'Pendiente de Pago'), (5, 'Pagada')], default=4, verbose_name='Estado'),
        ),
    ]
