# Generated by Django 6.0.4 on 2026-04-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_order_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='efectivo_entregado',
        ),
    ]
