# Generated by Django 6.0.4 on 2026-04-18 03:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría del Producto')),
                ('icono', models.CharField(choices=[('🍕', '🍕 Platos fuertes'), ('🥗', '🥗 Entradas'), ('🥤', '🥤 Bebidas'), ('🍰', '🍰 Postres'), ('🍔', '🍔 Hamburguesas'), ('🥩', '🥩 Carnes'), ('🍜', '🍜 Sopas'), ('🐟', '🐟 Pescados'), ('☕', '☕ Café'), ('🍺', '🍺 Cervezas'), ('🍷', '🍷 Vinos'), ('🍸', '🍸 Cocteles'), ('🍦', '🍦 Helados'), ('🥖', '🥖 Panadería'), ('🍳', '🍳 Desayunos'), ('📋', '📋 Todos')], default='🍽️', max_length=10)),
                ('orden', models.IntegerField(default=0, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionDiaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_operacion', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de memú')),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Producto')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.categoria', verbose_name='Categoría del Producto')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MenuProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_products', to='administracion.menu', verbose_name='Tipo de Menú')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.product')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['numero'], name='administrac_numero_6134d2_idx'), models.Index(fields=['activa'], name='administrac_activa_391ffe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['nombre'], name='administrac_nombre_3aa4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['disponible'], name='administrac_disponi_7cd2f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuproduct',
            constraint=models.UniqueConstraint(fields=('menu', 'producto'), name='unique_menu_producto'),
        ),
    ]
