# Generated by Django 6.0.4 on 2026-04-20 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_cocina_activo', models.BooleanField(default=False, help_text='Si está activo, los pedidos van primero a cocina. Si no, van directamente a caja.', verbose_name='Activar módulo de cocina')),
                ('pantalla_cocina_ip', models.GenericIPAddressField(blank=True, help_text='IP de la tablet/pantalla que mostrará los pedidos en cocina', null=True, verbose_name='IP de pantalla de cocina')),
                ('pantalla_cocina_puerto', models.IntegerField(default=8000, help_text='Puerto donde corre la app en la pantalla de cocina', verbose_name='Puerto de pantalla de cocina')),
                ('impresion_automatica', models.BooleanField(default=False, help_text='Imprime el ticket automáticamente al finalizar la orden', verbose_name='Imprimir ticket automáticamente')),
                ('impresora_nombre', models.CharField(blank=True, help_text='Nombre de la impresora térmica configurada en el sistema', max_length=100, null=True, verbose_name='Nombre de la impresora')),
                ('copias_ticket', models.PositiveSmallIntegerField(default=1, help_text='Número de copias a imprimir', verbose_name='Copias del ticket')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
