# Generated by Django 6.0.4 on 2026-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_configuracionsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsystem',
            name='licencia',
            field=models.CharField(default='demo', max_length=150),
        ),
    ]
